/*
 * This source file was generated by the Gradle 'init' task
 */
package proyecto_base_datos_ii;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
